name: build

on:
  push:
    branches:
      - main
    paths:
      - src/*
      - test/*
      - package.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: npm install
    - run: npm run build
    - run: npm test
    - run: npm run coverage
