name: CI

on:
  push:
    branches:
      - main
    paths:
      - package/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - run: yarn coverage
