name: test

on:
  push:
    branches:
      - main
    paths:
      - src/*
      - package.json
      - test/*

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.filter_paths.outputs.source }}
      package: ${{ steps.filter_paths.outputs.package }}
      test: ${{ steps.filter_paths.outputs.test }}

    steps:
    - name: Detect which paths have changed
      uses: dorny/paths-filter@v2.11.1
      id: filter_paths
      with:
        filters: |
          source: src/*
          package: package.json
          test: test/*

  run_tests:
    runs-on: ubuntu-latest
    needs: detect_changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Run build, test, and coverage
      run: |
        npm ci
        npm run build
        npm test
        npm run coverage

  create_release:
    runs-on: ubuntu-latest
    needs: [run_tests, detect_changes]
    if: ${{ needs.detect_changes.outputs.source == 'true' || needs.detect_changes.outputs.package == 'true' }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: bump_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.13.0
        with:
          name: Release ${{ steps.bump_version.outputs.new_tag }}
          tag: ${{ steps.bump_version.outputs.new_tag }}
          body: ${{ steps.bump_version.outputs.changelog }}
          generateReleaseNotes: true

  publish_package:
    runs-on: ubuntu-latest
    needs: create_release

    steps:
      - name: Publish to npm
        uses: js-devtools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
